package importer

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/getcrew44/crew44/daemon/internal/recruit"
)

func writeFile(t *testing.T, dir, rel, body string) {
	t.Helper()
	full := filepath.Join(dir, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestRunWrapsUpstreamRepoAndScansSkills(t *testing.T) {
	src := t.TempDir()
	writeFile(t, src, "README.md", "# Karpathy Skills\n\nWriting + reasoning.")
	writeFile(t, src, "skills/writing/SKILL.md", "---\nname: writing\n---\n# Writing\n")
	writeFile(t, src, "skills/reasoning/SKILL.md", "---\nname: reasoning\n---\n# Reasoning\n")
	writeFile(t, src, "fixtures/big.bin", "binary")
	out := filepath.Join(t.TempDir(), "wrapper")

	result, err := Run(Options{
		RepoURL:     "https://github.com/multica-ai/andrej-karpathy-skills",
		Name:        "Karpathy Skills",
		Description: "Wrapped Karpathy skills.",
		Version:     "1.0.0",
		Author:      "multica-ai",
		Tags:        []string{"writing", "reasoning"},
		OutputDir:   out,
	}, NewDirFetcher(src), nil)
	if err != nil {
		t.Fatal(err)
	}
	if result.OutputDir != out {
		t.Fatalf("output dir = %q, want %q", result.OutputDir, out)
	}
	for _, expected := range []string{
		"AGENT.md",
		"crew44-agent.json",
		"IMPORT_REPORT.md",
		"upstream/README.md",
		"upstream/skills/writing/SKILL.md",
		"upstream/skills/reasoning/SKILL.md",
	} {
		if _, err := os.Stat(filepath.Join(out, expected)); err != nil {
			t.Errorf("missing %s: %v", expected, err)
		}
	}
	if len(result.DetectedSkills) != 2 {
		t.Fatalf("detected skills = %+v", result.DetectedSkills)
	}
	for _, s := range result.DetectedSkills {
		if !strings.HasPrefix(s.Path, "upstream/skills/") {
			t.Errorf("skill path not under upstream/: %+v", s)
		}
	}

	manifestRaw, err := os.ReadFile(filepath.Join(out, "crew44-agent.json"))
	if err != nil {
		t.Fatal(err)
	}
	var m recruit.Manifest
	if err := json.Unmarshal(manifestRaw, &m); err != nil {
		t.Fatal(err)
	}
	if m.SourceType != recruit.SourceTypeUpstreamWrapper {
		t.Fatalf("source_type = %q", m.SourceType)
	}
	if m.Upstream == nil || m.Upstream.RepoURL != "https://github.com/multica-ai/andrej-karpathy-skills" {
		t.Fatalf("upstream block missing: %+v", m.Upstream)
	}
	if m.Payload == nil || len(m.Payload.Exclude) == 0 {
		t.Fatalf("wrapper manifest should ship default exclude globs: %+v", m.Payload)
	}
	if err := recruit.ValidateManifestForImporter(&m); err != nil {
		t.Fatalf("generated manifest fails validation: %v", err)
	}

	agentBody, err := os.ReadFile(filepath.Join(out, "AGENT.md"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(agentBody), "Karpathy Skills") {
		t.Errorf("AGENT.md missing name: %q", agentBody)
	}
	if !strings.Contains(string(agentBody), "upstream/") {
		t.Errorf("AGENT.md missing upstream reference: %q", agentBody)
	}

	if len(result.NextSteps) == 0 {
		t.Fatal("next steps empty")
	}
}

func TestRunNativeLayoutSkipsUpstreamWrapper(t *testing.T) {
	src := t.TempDir()
	writeFile(t, src, "AGENT.md", "# Native\n")
	writeFile(t, src, "skills/writing/SKILL.md", "---\nname: writing\n---\n# w\n")
	out := filepath.Join(t.TempDir(), "out")

	result, err := Run(Options{
		RepoURL:     "https://github.com/o/native",
		Name:        "Native",
		Description: "d",
		Version:     "1.0.0",
		OutputDir:   out,
		Native:      true,
	}, NewDirFetcher(src), nil)
	if err != nil {
		t.Fatal(err)
	}
	// The importer overwrites the upstream AGENT.md placeholder with
	// its template (writeNoOverwrite would have failed if it didn't);
	// confirm there's no upstream/ directory at all.
	if _, err := os.Stat(filepath.Join(out, "upstream")); err == nil {
		t.Fatal("native import should not produce upstream/")
	}
	if result.Manifest.SourceType != recruit.SourceTypeNative {
		t.Fatalf("source_type = %q", result.Manifest.SourceType)
	}
	if result.Manifest.Upstream != nil {
		t.Fatalf("native manifest should not carry upstream block: %+v", result.Manifest.Upstream)
	}
}

func TestRunRefusesNonEmptyOutputDir(t *testing.T) {
	out := t.TempDir()
	writeFile(t, out, "existing.txt", "x")
	_, err := Run(Options{
		RepoURL: "https://github.com/o/r", Name: "n", Description: "d", Version: "1.0.0", OutputDir: out,
	}, NewDirFetcher(t.TempDir()), nil)
	if err == nil || !strings.Contains(err.Error(), "not empty") {
		t.Fatalf("expected refusal on non-empty dir, got %v", err)
	}
}

// The generator hook overrides the AGENT.md body; templated fallback
// only runs when the generator returns an empty string.
func TestRunUsesGeneratorWhenProvided(t *testing.T) {
	src := t.TempDir()
	writeFile(t, src, "README.md", "# u\n")
	out := filepath.Join(t.TempDir(), "out")
	body := "# Generated by Test\n\nThis body came from the runtime adapter.\n"
	result, err := Run(Options{
		RepoURL: "https://github.com/o/r", Name: "n", Description: "d", Version: "1.0.0", OutputDir: out,
	}, NewDirFetcher(src), stubGenerator{body: body})
	if err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(result.AgentMDPath)
	if string(data) != body {
		t.Fatalf("AGENT.md = %q, want generator body", data)
	}
}

type stubGenerator struct{ body string }

func (s stubGenerator) GenerateAgentBody(ctx GenerateContext) (string, error) {
	return s.body, nil
}
